development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: <email@gmail.com>
  :password: <password>
  :enable_starttls_auto: true
production:
  :address: smtp.sendgrid.net
  :port: 587
  :authentication: plain
  :user_name: <user_name>
  :password: <password>
  :domain: <domain.com>
  :enable_starttls_auto: true